### ISSUE TITLE
How to close SSL verify?

### ISSUE THREAD

**Issue by Chick9N** [zerex290/sankaku#9]
Encountered with "Fatal error on SSL transport", and I am so confused in reading "sslproto.py", don't know how to cancel SSL.
![image](https://github.com/zerex290/sankaku/assets/88222209/1d39191b-bd1e-4023-87a8-e80884b55548)

> Traceback (most recent call last):
  File "E:\sankaku-main\venv\searchid.py", line 12, in <module>
    asyncio.run(main())
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "E:\sankaku-main\venv\searchid.py", line 9, in main
    post = await client.get_post(post_id)
  File "E:\sankaku-main\sankaku\clients\clients.py", line 315, in get_post
    return mdl.Post(**response.json)
  File "E:\sankaku-main\venv\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Post
reactions
  Extra inputs are not permitted [type=extra_forbidden, input_value=[], input_type=list]
    For further information visit https://errors.pydantic.dev/2.3/v/extra_forbidden
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001D56A140C10>
transport: <_ProactorSocketTransport fd=368 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 361, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000001D56891B130>
Traceback (most recent call last):
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 599, in _start_shutdown
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 604, in _write_appdata
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 712, in _process_write_backlog
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 726, in _fatal_error
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\86188\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

> import asyncio
from sankaku.clients import PostClient
async def main():
    client = PostClient()
    await client.login(access_token=r"") #censored
    post_id: int = 34326859  # Here the ID of the post you interested in
    post = await client.get_post(post_id)
    print(post.file_url)
asyncio.run(main())

**Comment by Chick9N** [comment]
It worked fine several days ago, though.

**Comment by zerex290** [comment]
According to following part in traceback I made a conclusion that an actual error is triggered because of new field in JSON response model from SankakuComplex servers:
> pydantic_core._pydantic_core.ValidationError: 1 validation error for Post
> reactions
> Extra inputs are not permitted [type=extra_forbidden, input_value=[], input_type=list]
> For further information visit https://errors.pydantic.dev/2.3/v/extra_forbidden

After updating some models (`PageBook` and `Post` models) I run library tests and all of them were passed. So i uploaded new version of `sankaku` to [PyPI](https://pypi.org/project/sankaku/) (v2.0.1).

Does your issue is still present after updating?

**Comment by Chick9N** [comment]
![image](https://github.com/zerex290/sankaku/assets/88222209/b340dab8-aabc-445a-8637-b6573bb13d97)
I' ve install the latest version of your sankaku package, but the problem still exsists

**Comment by Chick9N** [comment]
> E:\s2\pythonProject\venv\Scripts\Scripts\python.exe E:\s2\pythonProject\test.py 
Traceback (most recent call last):
  File "E:\s2\pythonProject\venv\Scripts\lib\site-packages\sankaku\clients\clients.py", line 48, in _login_via_access_token
    self._profile = await self._get_profile(access_token)
  File "E:\s2\pythonProject\venv\Scripts\lib\site-packages\sankaku\clients\clients.py", line 65, in _get_profile
    raise errors.SankakuServerError(
sankaku.errors.SankakuServerError: [401] Failed to get user profile: success=False, code=snackbar__common_unauthorized, error=snackbar__common_unauthorized, errorId=error_939fe9e3ebd73af3.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\s2\pythonProject\test.py", line 12, in <module>
    asyncio.run(main())
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "E:\s2\pythonProject\test.py", line 6, in main
    await client.login(access_token=r"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyNjIwMDQsInN1Ykx2bCI6MCwiaXNzIjoiaHR0cHM6Ly9jYXBpLXYyLnNhbmtha3Vjb21wbGV4LmNvbSIsInR5cGUiOiJCZWFyZXIiLCJhdWQiOiJjb21wbGV4Iiwic2NvcGUiOiJjb21wbGV4IiwiaWF0IjoxNjk0MzQ4MDg2LCJleHAiOjE2OTQ5NTI4ODZ9.hfQxLfQ9og2XMlrd1T5evh_EFttfZQBqIkU5-9mESuU")
  File "E:\s2\pythonProject\venv\Scripts\lib\site-packages\sankaku\clients\clients.py", line 90, in login
    await self._login_via_access_token(access_token)
  File "E:\s2\pythonProject\venv\Scripts\lib\site-packages\sankaku\clients\clients.py", line 53, in _login_via_access_token
    raise errors.AuthorizationError(e.status, **e.kwargs)
sankaku.errors.AuthorizationError: [401] Authorization failed: success=False, code=snackbar__common_unauthorized, error=snackbar__common_unauthorized, errorId=error_939fe9e3ebd73af3.
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001FB220D92B0>
transport: <_ProactorSocketTransport fd=844 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000001FB2094ECA0>
Traceback (most recent call last):
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 599, in _start_shutdown
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 604, in _write_appdata
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 712, in _process_write_backlog
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 726, in _fatal_error
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 751, in call_soon
  File "C:\Users\86188\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

Process finished with exit code 1

**Comment by zerex290** [comment]
Have you tried to login with username and password instead of access token?
Also what happens if you try to use library without logging in (for example, browsing posts or books)?

**Comment by Chick9N** [comment]
Yeah, it is the access token's problem.
It changes over time, OMG.
![image](https://github.com/zerex290/sankaku/assets/88222209/55e79108-70b7-4a19-856e-86bbce178efd)
(Lower line is the new access token.)

**Comment by zerex290** [comment]
If problem has gone away after using another access token, than old token had been expired, so the issue can be resolved.
